services:
  - type: web
    name: cacheme-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free  # Change to 'starter' or other plan as needed
    region: oregon  # Change to your preferred region
    branch: main
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # Set this manually in Render dashboard for security
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /api/metrics
    autoDeploy: true
